standard = "2008"

[libraries]
lib.files = [
    'E:/WorkSpace/python/data_analysis/python_DSP/hdl/tb/tb_fir_filter.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/hdl/src/fir_filter.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/hdl/src/counter.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/hdl/tb/tb_counter.vhd',
]

vunit_lib.files = [
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/string_ops/src/string_ops.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/path/src/path.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/logging/src/print_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/logging/src/location_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/logging/src/location_pkg-body-2008m.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/types.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/event_common_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/event_private_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/data_types_private_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/codec_builder.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/codec_builder-2008p.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/codec.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/codec-2008p.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/api/external_string_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/logging/src/ansi_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/logging/src/log_levels_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/byte_vector_ptr_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/api/external_integer_vector_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/logging/src/log_handler_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/logging/src/print_pkg-body.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/logging/src/file_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/logging/src/log_handler_pkg-body.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pkg-body-2002p.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/integer_array_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/queue_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/string_ptr_pool_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/queue_pkg-body.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/queue_pkg-2008p.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pool_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/queue_pool_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/integer_array_pkg-body.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/dict_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/dict_pkg-2008p.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/dict_pkg-body.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/data_types_context.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/core/src/stop_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/core/src/stop_body_2008p.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/core/src/core_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/logging/src/log_levels_pkg-body.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/id_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/logging/src/logger_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/logging/src/log_deprecated_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/dictionary/src/dictionary.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/run/src/run_types.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/run/src/runner_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/run/src/run_api.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/logging/src/logger_pkg-body.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/data_types/src/event_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/check/src/checker_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/run/src/run_deprecated_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/vunit_run_context.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/run/src/run.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/check/src/checker_pkg-body.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/check/src/check_api.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/check/src/check_deprecated_pkg.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/vunit_context.vhd',
    'E:/WorkSpace/python/data_analysis/python_DSP/.venv/Lib/site-packages/vunit/vhdl/check/src/check.vhd',
]
vunit_lib.is_third_party = true
